<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "exampleUiComponent": {
                    "component": "uiComponent",
                    "children": {
                        "child1": {
                            "component": "uiComponent",
                            "template": "Mage2tv_Js/info",
                            "displayArea": "groupA"
                        },
                        "child2": {
                            "component": "uiComponent",
                            "template": "Mage2tv_Js/info",
                            "displayArea": "groupB"
                        }
                    }
                }
            }
        }
    }
}
</script>
<div data-bind="scope: 'exampleUiComponent'">
    <!-- foreach: getRegion("groupA") -->
        <!-- ko template: getTemplate() --><!-- /ko -->
    <!-- /ko -->
</div>
