<script type="text/x-magento-init">
    {
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "component-a": {
                    "component": "Mage2tv_Js/js/import/ui-component-a",
                    "provider": "component-b",
                    "propertyValue": "amount"
                },
                "component-b": {
                    "component": "Mage2tv_Js/js/import/ui-component-b"
                }
            }
        }
    }
}
</script>
<div data-bind="scope: 'component-a'">
    <h3 data-bind="text: label"></h3>
    <div data-bind="text: amount"></div>
    <div data-bind="text: amountLink"></div>
</div>
<div data-bind="scope: 'component-b'">
    <h3 data-bind="text: label"></h3>
    <div data-bind="text: value"></div>
    <div data-bind="text: amount"></div>
    <div data-bind="text: valueLink"></div>
</div>