<h1 id="output">TEST</h1>
<div id="output_content"></div>

<script type="text/x-magento-init">
    {
        "#output": {
            "deanCustomContent": {
                "content": "#output_content",
                "collapsible": "#collapsible"
            }
        }
    }
</script>

<h2>KNOCKOUT PRACTICE</h2>
<div id="kodiv" data-bind="scope: 'knockoutPractice'">
    <span data-bind="text: title"></span>
</div>

<script type="text/x-magento-init">
        {
        "*": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "knockoutPractice": {
                        "component": "Dean_Override/js/knockout-practice",
                        "config": {
                            "title": "value-xmagentoinit"
                        }
                    }
                }
            }
        }
    }
</script>

<div class="dropdown-wrap">
    <button class="dropdown-button">
        <span><?= (__('Dropdown open button')) ?></span>
    </button>
    <div id="dropdown-dialog" data-role="dropdownDialog">
        <?= (__('Dropdown content')) ?>
    </div>
</div>

<script type="text/javascript">
    require([
        'jquery',
        'dropdownDialog'
        ], function($, dropdownDialog) {
            'use strict';

            $('#dropdown-dialog').dropdownDialog({
                appendTo: '.dropdown-wrap',
                triggerTarget: '.dropdown-button',
                closeOnMouseLeave: false,
                closeOnEscape: true,
                timeout: 2000,
                triggerClass: 'active',
                parentClass: 'active',
                buttons: [{
                    text: $.mage.__('Close'),
                    click: function () {
                        $(this).dropdownDialog("close");
                    }
                }]
            });
        }
    );
</script>